### ISSUE TITLE
Support for connection pools/ Missing AsyncResource

### ISSUE THREAD

**Issue by mcollina** [tc39-transfer/proposal-async-context#23]
[AsyncResource](https://nodejs.org/api/async_context.html#class-asyncresource) is a fundamental piece of the puzzle to support pools of sockets or similar. I don't see how this proposal handles that problem without it

**Comment by jridgewell** [comment]
We expose the static `AsyncContext.wrap()` method, which allows you to capture the current global state for all `AsyncContext` instances:

```js
const ctx = new AsyncContext();


const wrapped = ctx.run(1, () => {
  return AsyncContext.wrap((cb) => cb());
});

wrapped(() => {
  console.assert(ctx.get() === 1);
});

**Comment by legendecas** [comment]
`AsyncResource` is equivalent to `AsyncContext.wrap` as they all capture the current async context global state. However, compared to `AsyncResource`, `AsyncContext.wrap` requires a function to be wrapped, as discussed at https://github.com/tc39-transfer/proposal-async-context/issues/21.

**Comment by mcollina** [comment]
I'm closing this and will give feedback in #21.
